-- CreateTable
CREATE TABLE "game_businesses" (
    "id" SERIAL NOT NULL,
    "번호" INTEGER,
    "개방서비스명" TEXT,
    "개방서비스아이디" TEXT,
    "개방자치단체코드" TEXT,
    "관리번호" TEXT,
    "인허가일자" TEXT,
    "인허가취소일자" TEXT,
    "영업상태구분코드" TEXT,
    "영업상태명" TEXT,
    "상세영업상태코드" TEXT,
    "상세영업상태명" TEXT,
    "폐업일자" TEXT,
    "휴업시작일자" TEXT,
    "휴업종료일자" TEXT,
    "재개업일자" TEXT,
    "소재지전화" TEXT,
    "소재지면적" TEXT,
    "소재지우편번호" TEXT,
    "소재지전체주소" TEXT,
    "도로명전체주소" TEXT,
    "도로명우편번호" TEXT,
    "사업장명" TEXT,
    "최종수정시점" TEXT,
    "데이터갱신구분" TEXT,
    "데이터갱신일자" TEXT,
    "업태구분명" TEXT,
    "좌표정보x" TEXT,
    "좌표정보y" TEXT,
    "문화체육업종명" TEXT,
    "문화사업자구분명" TEXT,
    "총층수" TEXT,
    "주변환경명" TEXT,
    "제작취급품목내용" TEXT,
    "시설면적" TEXT,
    "지상층수" TEXT,
    "지하층수" TEXT,
    "건물용도명" TEXT,
    "통로너비" TEXT,
    "조명시설조도" TEXT,
    "노래방실수" TEXT,
    "청소년실수" TEXT,
    "비상계단여부" TEXT,
    "비상구여부" TEXT,
    "자동환기여부" TEXT,
    "청소년실여부" TEXT,
    "특수조명여부" TEXT,
    "방음시설여부" TEXT,
    "비디오재생기명" TEXT,
    "조명시설유무" TEXT,
    "음향시설여부" TEXT,
    "편의시설여부" TEXT,
    "소방시설여부" TEXT,
    "총게임기수" TEXT,
    "기존게임업외업종명" TEXT,
    "제공게임물명" TEXT,
    "공연장형태구분명" TEXT,
    "품목명" TEXT,
    "최초등록시점" TEXT,
    "지역구분명" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "game_businesses_pkey" PRIMARY KEY ("id")
);
